FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app source code into the container
COPY . .

# Expose port 5000 to the outside world
EXPOSE 5050

# Run the app when the container starts
CMD ["python", "-u", "app.py"]
